---

- name: Configure SCD Platform Model 
  hosts: "{{ target }}"
  
  connection: winrm
  port: 5986
  gather_facts: false
  
  vars_files: host_vars/SCD.yml

  roles:
    - role: ConfigurePlatformModel
      when: inventory_hostname in groups ['Primary_MUCS']

