---

- name: Configure SCD Core components on primary node and Install Agents
  hosts: "{{ target }}"

  connection: winrm
  port: 5986
  gather_facts: false

  vars:
    Tool_state: Install
  vars_files: host_vars/SCD.yml

  roles:
    - role: ConfigureSCDCore_MUCS
      when: inventory_hostname in groups ['Primary_MUCS']
   
